baseURL = 'http://educational-help.com'
languageCode = 'en-us'
title = 'Educational Help Centers - Tutoring Services'

[menu]

    [[menu.main]]
    name = "Home"
    URL = "/"
    weight = 5

    [[menu.main]]
    name = "Programs"
    URL = "/services"
    weight = 10

    [[menu.main]]
    name = "History"
    URL = "/about"
    weight = 15

    [[menu.main]]
    name = "Locations"
    URL = "/contact"
    weight = 20

    [[menu.main]]
    name = "Resources"
    URL = "/books"
    weight = 25

    [[menu.main]]
    name = "Fees"
    URL = "/pricing"
    weight = 30

    [[menu.main]]
    name = "Registration"
    URL = "/registration"
    weight = 35

[params]
    
